version: 0.0
os: linux
files:
  - source: /
    destination: /var/www/html/
file_exists_behavior: OVERWRITE
hooks:
  AfterInstall:
    - location: images/install_apache.sh
      timeout: 180
      runas: root
  ApplicationStart:
    - location: images/start_apache2.sh
      timeout: 180
      runas: root
