version: 1.1
os: linux
files:
  - source: /
    destination: /var/www/html/
hooks:
  AfterInstall:
    - location: scripts/install_apache.sh
      timeout: 300
      runas: root
  ApplicationStart:
    - location: scripts/start_apache2.sh
      timeout: 300
      runas: root
